### ISSUE TITLE
关于编译

### ISSUE THREAD

**Issue by beta-Cyg** [WarfarinBloodanger/ff0-script#2]
麻烦神犇加个makefile好吗，搞不清楚该编译哪个文件啊

**Comment by WarfarinBloodanger** [comment]
随便挑一个 cpp 直接编译就可以了~





这里的目录代表的是版本号，比如 “ff0-3-00" 表示的是 3.00 版本的 FF0Script，每个版本都是独立的。


里面的 FF0.cpp (早期版本叫 Warfarin.cpp) 直接编译成exe运行就行了。


任何一个 cpp 文件都能直接编译成为 exe。因为我比较懒qaq 不想写makefile。


况且信息竞赛的代码是不需要写 makefile 的，所以从来就没有用过 makefile（简单来说，就是我不会）











在 2021-08-23 14:59:53，"宋远之" ***@***.***> 写道：

麻烦神犇加个makefile好吗，搞不清楚该编译哪个文件啊

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by beta-Cyg** [comment]
其实主要是之后项目大了之后可能会有很多文件，Makefile能更好地来编译项目（而且自己调试的时候只需要打make就好了，我也懒
但既然这样就算了吧！

从 Windows 版邮件发送

发件人: WarfarinBloodanger
发送时间: 2021年8月24日 8:38
收件人: WarfarinBloodanger/ff0-script
抄送: 宋远之; Author
主题: Re: [WarfarinBloodanger/ff0-script] 关于编译 (#2)

随便挑一个 cpp 直接编译就可以了~





这里的目录代表的是版本号，比如 “ff0-3-00" 表示的是 3.00 版本的 FF0Script，每个版本都是独立的。


里面的 FF0.cpp (早期版本叫 Warfarin.cpp) 直接编译成exe运行就行了。


任何一个 cpp 文件都能直接编译成为 exe。因为我比较懒qaq 不想写makefile。


况且信息竞赛的代码是不需要写 makefile 的，所以从来就没有用过 makefile（简单来说，就是我不会）











在 2021-08-23 14:59:53，"宋远之" ***@***.***> 写道：

麻烦神犇加个makefile好吗，搞不清楚该编译哪个文件啊

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
